// Comic Con Tracker V17.0 - generic refresh engine
// Non-hardcoded parser for current and future conventions.
const FIRECRAWL_API_KEY=process.env.FIRECRAWL_API_KEY||'';
const MONTH={jan:0,january:0,feb:1,february:1,mar:2,march:2,apr:3,april:3,may:4,jun:5,june:5,jul:6,july:6,aug:7,august:7,sep:8,sept:8,september:8,oct:9,october:9,nov:10,november:10,dec:11,december:11};
const junkRx=/\b(policy|privacy|cookie|contact|customer service|subscribe|newsletter|learn more|read on|hotel|travel|floor plan|visit|exhibit|exhibitor|media inquiries|rewards|discounts|coupons|mobile app|about us|terms|back to top|social|tickets|ticket|buy|shop|merch|sponsor|parking|faq|menu|navigation|volunteer|application|apply|login|account|service|show info|see all|sign up|join us)\b/i;
const exactJunk=new Set(['about us','autograph sessions','back to top','buy tickets','contact us','cookie policy','customer service','discounts coupons','discounts and coupons','every hero deserves a reward','fan ambassador','fan meetups','floor plan','getting here','join us','learn more','like and subscribe','media inquiries','mobile app','past exhibitors','plan your visit','privacy policy','read on','see all celebrities','see the magic','sign up','stay connected','stay up to date','suggest a guest','superfan rewards','terms of use','three days of','travel hotels','travel and hotels','want to exhibit','we re social','animation voices','comic creators','professional creators','sci fi fantasy','show info','ticket information','photo ops','newsletter','main events','cosplay','gaming','anime','artist alley','view all']);
function norm(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim().replace(/^nicholas cage$/,'nicolas cage')}
function clean(s=''){return String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<svg[\s\S]*?<\/svg>/gi,' ').replace(/<nav[\s\S]*?<\/nav>/gi,' ').replace(/<header[\s\S]*?<\/header>/gi,' ').replace(/<footer[\s\S]*?<\/footer>/gi,' ').replace(/<[^>]+>/g,'\n').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/&#x27;|&#39;/g,"'").replace(/&quot;/g,'"').replace(/\r/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
function guid(){return globalThis.crypto?.randomUUID?crypto.randomUUID():'id-'+Math.random().toString(36).slice(2)+Date.now()}
function initials(n){return String(n||'?').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function isJunkGuestName(name=''){const n=norm(name);return !n||exactJunk.has(n)||junkRx.test(name)||/^(guest|guests|celebrity|celebrities|comic creators?|animation voices?|voice actors?|sci fi|fantasy)$/i.test(String(name).trim())}
function looksGuest(name=''){const s=String(name||'').replace(/\s+/g,' ').trim();if(/^J\.?\s*R\.?\s*Ward$/i.test(s)||/^JR\s*Ward$/i.test(s))return true;if(isJunkGuestName(s)||s.length<4||s.length>70)return false;if(/[,#$]|\$|https?:|@|:|\/|\\|\||\d{3,}/i.test(s))return false;const w=s.split(/\s+/).filter(Boolean);if(w.length<2||w.length>5)return false;if(s===s.toUpperCase()&&w.length>=3)return false;return /^[A-Za-zÀ-ÖØ-öø-ÿ'.\- ]+$/.test(s)}
function normalizeUrl(raw,base){try{return new URL(String(raw||'').trim(),base||undefined).href.split('#')[0]}catch{return''}}
function sameHost(a,b){try{return new URL(a).host.replace(/^www\./,'')===new URL(b).host.replace(/^www\./,'')}catch{return false}}
function siteRoot(u){try{const x=new URL(u);return `${x.protocol}//${x.host}/`}catch{return u||''}}
function badUrl(u=''){return /facebook|instagram|x\.com|twitter|youtube|tiktok|mailto:|javascript:|tel:|privacy|cookie|terms|login|account|shop|cart|newsletter|sponsor|exhibitor|volunteer|media|press|floor-plan|mobile-app|hotel|travel|parking|contact/i.test(String(u))}
function links(raw,base){const out=new Set(),s=String(raw||''),pieces=[...(s.match(/https?:\/\/[^\s"'<>\)]+/gi)||[]),...[...s.matchAll(/href=["']([^"']+)["']/gi)].map(m=>m[1]),...[...s.matchAll(/\[[^\]]+\]\(([^\)]+)\)/g)].map(m=>m[1])];for(const p of pieces){const u=normalizeUrl(p,base);if(!u||badUrl(u))continue;if(sameHost(u,base)||sameHost(u,siteRoot(base)))out.add(u)}return[...out]}
function guestLinks(raw,base){return links(raw,base).filter(u=>/guest|guests|celebrity|celebrities|comic-creator|creators|voice|actor|artist|author|professional/i.test(u)).slice(0,10)}
function metaLinks(raw,base){return [base,siteRoot(base),...links(raw,base).filter(u=>/about|show-info|info|attend|visit|venue|faq|getting-here|home|plan/i.test(u)).slice(0,8)].filter(Boolean)}
async function scrape(url){if(!url)return{raw:'',text:'',method:'none'};if(FIRECRAWL_API_KEY){try{const r=await fetch('https://api.firecrawl.dev/v2/scrape',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${FIRECRAWL_API_KEY}`},body:JSON.stringify({url,formats:['markdown','html','links'],onlyMainContent:false,waitFor:3500,timeout:60000,removeBase64Images:true})});const j=await r.json().catch(()=>({}));if(r.ok&&j.success){const raw=[j.data?.markdown,j.data?.html,Array.isArray(j.data?.links)?j.data.links.join('\n'):''].filter(Boolean).join('\n');return{raw,text:clean(raw),method:'firecrawl'}}}catch(e){}}try{const r=await fetch(url,{headers:{'user-agent':'ComicConTracker/17.0 refresh'}});if(!r.ok)throw new Error(String(r.status));const raw=await r.text();return{raw,text:clean(raw),method:'direct'}}catch(e){return{raw:'',text:'',method:'failed',warning:e.message}}}
function parseGuests(raw,sourceUrl){const map=new Map();for(const line of clean(raw).split(/\n+/).map(x=>x.replace(/^#+\s*/,'').replace(/[*_`]/g,'').replace(/\s+/g,' ').trim()).filter(Boolean)){const name=line.replace(/\s+-\s+appearing.*$/i,'').replace(/\s+appearing\s+(thursday|friday|saturday|sunday).*$/i,'').replace(/\s+(autograph|photo op|panel).*$/i,'').trim();if(looksGuest(name)&&!map.has(norm(name)))map.set(norm(name),{name,fandom:'Guest',days:['TBD'],auto:0,photo:0,photoUrl:'',source:'Verified parser',sourceUrl})}return[...map.values()]}
function iso(y,m,d){y=Number(y);d=Number(d);if(!Number.isFinite(y)||!Number.isFinite(d)||m==null||y<2020||y>2100||d<1||d>31)return'';const dt=new Date(Date.UTC(y,m,d));return dt.getUTCMonth()===m&&dt.getUTCDate()===d?dt.toISOString().slice(0,10):''}
function fmtRange(s,e){if(!s)return'TBD';const opt={month:'short',day:'numeric',timeZone:'UTC'},sd=new Date(s+'T00:00:00Z'),ed=e?new Date(e+'T00:00:00Z'):null;if(ed&&!Number.isNaN(ed.getTime())&&e!==s)return `${sd.toLocaleDateString('en-CA',opt)} - ${ed.toLocaleDateString('en-CA',opt)}, ${sd.getUTCFullYear()}`;return `${sd.toLocaleDateString('en-CA',opt)}, ${sd.getUTCFullYear()}`}
function parseDates(t){t=clean(t).replace(/\s+/g,' ');const mw='Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:t|tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?';let m=t.match(new RegExp(`\\b(${mw})\\s+(\\d{1,2})\\s*(?:-|–|—|to)\\s*(?:(${mw})\\s+)?(\\d{1,2}),?\\s*(20\\d{2})`,'i'));if(m){const sm=MONTH[m[1].toLowerCase().slice(0,3)]??MONTH[m[1].toLowerCase()],em=MONTH[(m[3]||m[1]).toLowerCase().slice(0,3)]??MONTH[(m[3]||m[1]).toLowerCase()],s=iso(m[5],sm,m[2]),e=iso(m[5],em,m[4]);if(s)return{startDate:s,endDate:e||s,dates:fmtRange(s,e||s)}}m=t.match(new RegExp(`\\b(${mw})\\s+(\\d{1,2}),?\\s*(20\\d{2})`,'i'));if(m){const sm=MONTH[m[1].toLowerCase().slice(0,3)]??MONTH[m[1].toLowerCase()],s=iso(m[3],sm,m[2]);if(s)return{startDate:s,endDate:s,dates:fmtRange(s,s)}}return{startDate:'',endDate:'',dates:''}}
function venue(text,fallback=''){const bad=/\b(cookie|privacy|terms|contact|subscribe|newsletter|tickets|guest|autograph|photo op|facebook|instagram)\b/i,good=/\b(convention centre|convention center|expo centre|expo center|exhibition centre|exhibition center|conference centre|conference center|stampede park|javits|event centre|event center|arena|hall|pavilion|fairgrounds|venue)\b/i;for(const line of clean(text).split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean)){if(line.length>=5&&line.length<=120&&!bad.test(line)&&good.test(line))return line}const m=clean(text).match(/(?:venue|location)\s*:?\s*([^\n]{5,120})/i);return m&&!bad.test(m[1])?m[1].trim():fallback||'TBD'}
function city(text,c,fallback=''){if(fallback&&fallback!=='TBD')return fallback;const n=String(c?.name||'').match(/\b(Edmonton|Calgary|Vancouver|Toronto|Montreal|New York|Seattle|Los Angeles|Chicago|Orlando|Ottawa|Winnipeg|Halifax)\b/i);if(n)return n[1];const m=clean(text).match(/\b(Vancouver|Edmonton|Calgary|Toronto|Montreal|New York|Seattle|Los Angeles|Chicago|Orlando|Ottawa|Winnipeg|Halifax)\b/i);return m?m[1]:fallback||'TBD'}
function merge(existing=[],fresh=[]){const changes=[],map=new Map();for(const g of existing||[]){if(!looksGuest(g?.name)){if(g?.name)changes.push({type:'removedNonGuest',name:g.name});continue}map.set(norm(g.name),{...g})}for(const g of fresh||[]){if(!looksGuest(g.name))continue;const k=norm(g.name),old=map.get(k);if(!old){map.set(k,{id:guid(),must:false,hidden:false,img:initials(g.name),schedule:'TBD',firstSeen:new Date().toISOString(),lastSeen:new Date().toISOString(),...g});changes.push({type:'newGuest',name:g.name})}else map.set(k,{...old,...g,id:old.id,must:old.must===true,hidden:old.hidden===true,img:old.img||initials(g.name),schedule:old.schedule||g.schedule||'TBD',days:Array.isArray(old.days)&&old.days.length&&!old.days.every(x=>String(x).toUpperCase()==='TBD')?old.days:g.days,auto:old.auto||g.auto||0,photo:old.photo||g.photo||0,photoUrl:old.photoUrl||g.photoUrl||'',firstSeen:old.firstSeen||new Date().toISOString(),lastSeen:new Date().toISOString()})}return{guests:[...map.values()],changes}}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{const{convention}=req.body||{};if(!convention)return res.status(400).json({error:'Missing convention'});const mainUrl=convention.website||convention.guestUrl||'',guestUrl=convention.guestUrl||convention.website||'';if(!mainUrl&&!guestUrl)return res.status(400).json({error:'Convention needs a website or guest URL'});const main=await scrape(mainUrl||guestUrl),first=guestUrl&&guestUrl!==mainUrl?await scrape(guestUrl):main;const gpages=[first];for(const u of guestLinks([main.raw,first.raw].join('\n'),mainUrl||guestUrl).slice(0,6))if(u!==guestUrl&&u!==mainUrl)gpages.push(await scrape(u));const mpages=[main];for(const u of metaLinks(main.raw,mainUrl||guestUrl).slice(0,6))if(u!==mainUrl&&u!==guestUrl)mpages.push(await scrape(u));const fresh=[...new Map(gpages.flatMap(p=>parseGuests(p.raw||p.text,guestUrl||mainUrl)).map(g=>[norm(g.name),g])).values()];const merged=merge(convention.guests||[],fresh);const combined=mpages.map(p=>p.text||p.raw).join('\n');const pd=parseDates(combined),prev=convention.startDate||convention.start||'',startDate=pd.startDate||prev||'',endDate=pd.endDate||convention.endDate||'';const eventRollover=Boolean(pd.startDate&&prev&&pd.startDate!==prev);return res.status(200).json({convention:{...convention,city:city(combined,convention,convention.city),dates:pd.dates||convention.dates||'TBD',startDate,endDate,start:startDate,venue:venue(combined,convention.venue),website:mainUrl,guestUrl,guests:merged.guests,guestStatus:merged.guests.length?`${merged.guests.filter(g=>!g.hidden).length} active guest(s)`:'No guests announced yet',previousStartDate:eventRollover?prev:convention.previousStartDate||'',eventCycleUpdatedAt:eventRollover?new Date().toISOString():convention.eventCycleUpdatedAt||'',lastChecked:new Date().toISOString(),refreshStatus:'updated'},changes:merged.changes,parsedGuestCount:fresh.length,methods:{guestPage:gpages.map(p=>p.method).join(','),mainPage:mpages.map(p=>p.method).join(',')},warnings:[main.warning,first.warning,...gpages.map(p=>p.warning),...mpages.map(p=>p.warning)].filter(Boolean),hasFirecrawlKey:Boolean(FIRECRAWL_API_KEY),photosFound:0,mode:'generic-current-future-parser'})}catch(e){return res.status(500).json({error:e.message||'Refresh failed'})}}
